title: "DzPmx 的博客"
description: "欢迎来到 DzPmx 的个人博客。"
author: DzPmx
url: "https://dzpmx.github.io"
baseurl: ""
lang: zh-CN
timezone: Asia/Shanghai
github_username: DzPmx

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
